spring:
 cloud:
  gateway:
   discovery:
    locator: 
     enabled: false
     lowerCaseServiceId: true
   routes:
   - id: feign
     uri: lb://eureka-feign
     predicates:
     - Path=/eureka-feign/**
     filters:
     - StripPrefix=1 

 

