spring:
 application:
  name: eureka-gateway
 cloud:
  gateway:
   discovery:
    locator: 
     enabled: true
     lowerCaseServiceId: true
   routes:
   - id: feign
     uri: lb://eureka-feign
     predicates:
     - Path=/eureka-feign/**
     filters:
     - StripPrefix=1 

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/
 

